admin_painting:
    resource: "@AdminBundle/Resources/config/routing/painting.yml"
    prefix:   /painting
admin_category:
    resource: "@AdminBundle/Resources/config/routing/category.yml"
    prefix:   /category
admin_subcategory:
    resource: "@AdminBundle/Resources/config/routing/subcategory.yml"
    prefix:   /subcategory
admin_post:
    resource: "@AdminBundle/Resources/config/routing/post.yml"
    prefix:   /post
admin_become_admin:
    path:     /become-admin
    defaults: { _controller: "AdminBundle:Admin:becomeAdmin" }
admin_index:
    path:     /
    defaults: { _controller: "AdminBundle:Default:index" }

