<?php

namespace AdminBundle\Repository;

use AdminBundle\Entity\Category;

/**
 * SubcategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubcategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function getByCategoryAndSlug(Category $category, $slug)
    {
        $qb = $this->createQueryBuilder('subcat')
            ->addSelect('p')
            ->innerJoin('subcat.paintings', 'p')
            ->where('subcat.category = :category')
            ->andWhere('subcat.slug = :slug')
            ->orderBy('p.createdAt', 'ASC')
            ->addOrderBy('p.title', 'ASC')
            ->setParameter('slug', $slug)
            ->setParameter('category', $category)
        ;

        return $qb->getQuery()->getOneOrNullResult();
    }
}
