subcategory_index:
    path:     /
    defaults: { _controller: "AdminBundle:Subcategory:index" }
    methods:  GET

subcategory_show:
    path:     /{id}/show
    defaults: { _controller: "AdminBundle:Subcategory:show" }
    methods:  GET

subcategory_new:
    path:     /new
    defaults: { _controller: "AdminBundle:Subcategory:new" }
    methods:  [GET, POST]

subcategory_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminBundle:Subcategory:edit" }
    methods:  [GET, POST]

subcategory_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminBundle:Subcategory:delete" }
    methods:  DELETE
